#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_QuanLyNhaThuoc
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLQBT")]
	public partial class QLQTDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCT_HoaDon(CT_HoaDon instance);
    partial void UpdateCT_HoaDon(CT_HoaDon instance);
    partial void DeleteCT_HoaDon(CT_HoaDon instance);
    partial void InsertThuoc(Thuoc instance);
    partial void UpdateThuoc(Thuoc instance);
    partial void DeleteThuoc(Thuoc instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLoThuoc(LoThuoc instance);
    partial void UpdateLoThuoc(LoThuoc instance);
    partial void DeleteLoThuoc(LoThuoc instance);
    partial void InsertNhaCungCap(NhaCungCap instance);
    partial void UpdateNhaCungCap(NhaCungCap instance);
    partial void DeleteNhaCungCap(NhaCungCap instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertNhomThuoc(NhomThuoc instance);
    partial void UpdateNhomThuoc(NhomThuoc instance);
    partial void DeleteNhomThuoc(NhomThuoc instance);
    #endregion
		
		public QLQTDataContext() : 
				base(global::DAL_QuanLyNhaThuoc.Properties.Settings.Default.QLQBTConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QLQTDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLQTDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLQTDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLQTDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CT_HoaDon> CT_HoaDons
		{
			get
			{
				return this.GetTable<CT_HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<Thuoc> Thuocs
		{
			get
			{
				return this.GetTable<Thuoc>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LoThuoc> LoThuocs
		{
			get
			{
				return this.GetTable<LoThuoc>();
			}
		}
		
		public System.Data.Linq.Table<NhaCungCap> NhaCungCaps
		{
			get
			{
				return this.GetTable<NhaCungCap>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<NhomThuoc> NhomThuocs
		{
			get
			{
				return this.GetTable<NhomThuoc>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_HoaDon")]
	public partial class CT_HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHD;
		
		private string _maThuoc;
		
		private System.Nullable<int> _soLuong;
		
		private System.Nullable<double> _gia;
		
		private string _donViTinh;
		
		private System.Nullable<double> _vAT;
		
		private EntityRef<Thuoc> _Thuoc;
		
		private EntityRef<HoaDon> _HoaDon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDChanging(string value);
    partial void OnmaHDChanged();
    partial void OnmaThuocChanging(string value);
    partial void OnmaThuocChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    partial void OngiaChanging(System.Nullable<double> value);
    partial void OngiaChanged();
    partial void OndonViTinhChanging(string value);
    partial void OndonViTinhChanged();
    partial void OnvATChanging(System.Nullable<double> value);
    partial void OnvATChanged();
    #endregion
		
		public CT_HoaDon()
		{
			this._Thuoc = default(EntityRef<Thuoc>);
			this._HoaDon = default(EntityRef<HoaDon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHD", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHD
		{
			get
			{
				return this._maHD;
			}
			set
			{
				if ((this._maHD != value))
				{
					if (this._HoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHDChanging(value);
					this.SendPropertyChanging();
					this._maHD = value;
					this.SendPropertyChanged("maHD");
					this.OnmaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maThuoc", DbType="VarChar(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maThuoc
		{
			get
			{
				return this._maThuoc;
			}
			set
			{
				if ((this._maThuoc != value))
				{
					if (this._Thuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaThuocChanging(value);
					this.SendPropertyChanging();
					this._maThuoc = value;
					this.SendPropertyChanged("maThuoc");
					this.OnmaThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Float")]
		public System.Nullable<double> gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donViTinh", DbType="NVarChar(10)")]
		public string donViTinh
		{
			get
			{
				return this._donViTinh;
			}
			set
			{
				if ((this._donViTinh != value))
				{
					this.OndonViTinhChanging(value);
					this.SendPropertyChanging();
					this._donViTinh = value;
					this.SendPropertyChanged("donViTinh");
					this.OndonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vAT", DbType="Float")]
		public System.Nullable<double> vAT
		{
			get
			{
				return this._vAT;
			}
			set
			{
				if ((this._vAT != value))
				{
					this.OnvATChanging(value);
					this.SendPropertyChanging();
					this._vAT = value;
					this.SendPropertyChanged("vAT");
					this.OnvATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_CT_HoaDon", Storage="_Thuoc", ThisKey="maThuoc", OtherKey="maThuoc", IsForeignKey=true)]
		public Thuoc Thuoc
		{
			get
			{
				return this._Thuoc.Entity;
			}
			set
			{
				Thuoc previousValue = this._Thuoc.Entity;
				if (((previousValue != value) 
							|| (this._Thuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thuoc.Entity = null;
						previousValue.CT_HoaDons.Remove(this);
					}
					this._Thuoc.Entity = value;
					if ((value != null))
					{
						value.CT_HoaDons.Add(this);
						this._maThuoc = value.maThuoc;
					}
					else
					{
						this._maThuoc = default(string);
					}
					this.SendPropertyChanged("Thuoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_CT_HoaDon", Storage="_HoaDon", ThisKey="maHD", OtherKey="maHD", IsForeignKey=true)]
		public HoaDon HoaDon
		{
			get
			{
				return this._HoaDon.Entity;
			}
			set
			{
				HoaDon previousValue = this._HoaDon.Entity;
				if (((previousValue != value) 
							|| (this._HoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDon.Entity = null;
						previousValue.CT_HoaDons.Remove(this);
					}
					this._HoaDon.Entity = value;
					if ((value != null))
					{
						value.CT_HoaDons.Add(this);
						this._maHD = value.maHD;
					}
					else
					{
						this._maHD = default(string);
					}
					this.SendPropertyChanged("HoaDon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thuoc")]
	public partial class Thuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maThuoc;
		
		private string _tenThuoc;
		
		private string _maNhomThuoc;
		
		private System.Nullable<bool> _loaiThuoc;
		
		private string _hoatChatChinh;
		
		private System.Nullable<bool> _trangThai;
		
		private EntitySet<CT_HoaDon> _CT_HoaDons;
		
		private EntitySet<LoThuoc> _LoThuocs;
		
		private EntityRef<NhomThuoc> _NhomThuoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaThuocChanging(string value);
    partial void OnmaThuocChanged();
    partial void OntenThuocChanging(string value);
    partial void OntenThuocChanged();
    partial void OnmaNhomThuocChanging(string value);
    partial void OnmaNhomThuocChanged();
    partial void OnloaiThuocChanging(System.Nullable<bool> value);
    partial void OnloaiThuocChanged();
    partial void OnhoatChatChinhChanging(string value);
    partial void OnhoatChatChinhChanged();
    partial void OntrangThaiChanging(System.Nullable<bool> value);
    partial void OntrangThaiChanged();
    #endregion
		
		public Thuoc()
		{
			this._CT_HoaDons = new EntitySet<CT_HoaDon>(new Action<CT_HoaDon>(this.attach_CT_HoaDons), new Action<CT_HoaDon>(this.detach_CT_HoaDons));
			this._LoThuocs = new EntitySet<LoThuoc>(new Action<LoThuoc>(this.attach_LoThuocs), new Action<LoThuoc>(this.detach_LoThuocs));
			this._NhomThuoc = default(EntityRef<NhomThuoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maThuoc", DbType="VarChar(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maThuoc
		{
			get
			{
				return this._maThuoc;
			}
			set
			{
				if ((this._maThuoc != value))
				{
					this.OnmaThuocChanging(value);
					this.SendPropertyChanging();
					this._maThuoc = value;
					this.SendPropertyChanged("maThuoc");
					this.OnmaThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenThuoc", DbType="NVarChar(20)")]
		public string tenThuoc
		{
			get
			{
				return this._tenThuoc;
			}
			set
			{
				if ((this._tenThuoc != value))
				{
					this.OntenThuocChanging(value);
					this.SendPropertyChanging();
					this._tenThuoc = value;
					this.SendPropertyChanged("tenThuoc");
					this.OntenThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhomThuoc", DbType="VarChar(5)")]
		public string maNhomThuoc
		{
			get
			{
				return this._maNhomThuoc;
			}
			set
			{
				if ((this._maNhomThuoc != value))
				{
					if (this._NhomThuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhomThuocChanging(value);
					this.SendPropertyChanging();
					this._maNhomThuoc = value;
					this.SendPropertyChanged("maNhomThuoc");
					this.OnmaNhomThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiThuoc", DbType="Bit")]
		public System.Nullable<bool> loaiThuoc
		{
			get
			{
				return this._loaiThuoc;
			}
			set
			{
				if ((this._loaiThuoc != value))
				{
					this.OnloaiThuocChanging(value);
					this.SendPropertyChanging();
					this._loaiThuoc = value;
					this.SendPropertyChanged("loaiThuoc");
					this.OnloaiThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoatChatChinh", DbType="NVarChar(20)")]
		public string hoatChatChinh
		{
			get
			{
				return this._hoatChatChinh;
			}
			set
			{
				if ((this._hoatChatChinh != value))
				{
					this.OnhoatChatChinhChanging(value);
					this.SendPropertyChanging();
					this._hoatChatChinh = value;
					this.SendPropertyChanged("hoatChatChinh");
					this.OnhoatChatChinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Bit")]
		public System.Nullable<bool> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_CT_HoaDon", Storage="_CT_HoaDons", ThisKey="maThuoc", OtherKey="maThuoc")]
		public EntitySet<CT_HoaDon> CT_HoaDons
		{
			get
			{
				return this._CT_HoaDons;
			}
			set
			{
				this._CT_HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_LoThuoc", Storage="_LoThuocs", ThisKey="maThuoc", OtherKey="maThuoc")]
		public EntitySet<LoThuoc> LoThuocs
		{
			get
			{
				return this._LoThuocs;
			}
			set
			{
				this._LoThuocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomThuoc_Thuoc", Storage="_NhomThuoc", ThisKey="maNhomThuoc", OtherKey="maNhomThuoc", IsForeignKey=true)]
		public NhomThuoc NhomThuoc
		{
			get
			{
				return this._NhomThuoc.Entity;
			}
			set
			{
				NhomThuoc previousValue = this._NhomThuoc.Entity;
				if (((previousValue != value) 
							|| (this._NhomThuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomThuoc.Entity = null;
						previousValue.Thuocs.Remove(this);
					}
					this._NhomThuoc.Entity = value;
					if ((value != null))
					{
						value.Thuocs.Add(this);
						this._maNhomThuoc = value.maNhomThuoc;
					}
					else
					{
						this._maNhomThuoc = default(string);
					}
					this.SendPropertyChanged("NhomThuoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_HoaDons(CT_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = this;
		}
		
		private void detach_CT_HoaDons(CT_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = null;
		}
		
		private void attach_LoThuocs(LoThuoc entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = this;
		}
		
		private void detach_LoThuocs(LoThuoc entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHD;
		
		private System.Nullable<System.DateTime> _ngayLapHD;
		
		private System.Nullable<bool> _loaiHD;
		
		private string _ghiChu;
		
		private string _maNV;
		
		private string _maKH;
		
		private EntitySet<CT_HoaDon> _CT_HoaDons;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDChanging(string value);
    partial void OnmaHDChanged();
    partial void OnngayLapHDChanging(System.Nullable<System.DateTime> value);
    partial void OnngayLapHDChanged();
    partial void OnloaiHDChanging(System.Nullable<bool> value);
    partial void OnloaiHDChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    #endregion
		
		public HoaDon()
		{
			this._CT_HoaDons = new EntitySet<CT_HoaDon>(new Action<CT_HoaDon>(this.attach_CT_HoaDons), new Action<CT_HoaDon>(this.detach_CT_HoaDons));
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHD", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHD
		{
			get
			{
				return this._maHD;
			}
			set
			{
				if ((this._maHD != value))
				{
					this.OnmaHDChanging(value);
					this.SendPropertyChanging();
					this._maHD = value;
					this.SendPropertyChanged("maHD");
					this.OnmaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLapHD", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayLapHD
		{
			get
			{
				return this._ngayLapHD;
			}
			set
			{
				if ((this._ngayLapHD != value))
				{
					this.OnngayLapHDChanging(value);
					this.SendPropertyChanging();
					this._ngayLapHD = value;
					this.SendPropertyChanged("ngayLapHD");
					this.OnngayLapHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiHD", DbType="Bit")]
		public System.Nullable<bool> loaiHD
		{
			get
			{
				return this._loaiHD;
			}
			set
			{
				if ((this._loaiHD != value))
				{
					this.OnloaiHDChanging(value);
					this.SendPropertyChanging();
					this._loaiHD = value;
					this.SendPropertyChanged("loaiHD");
					this.OnloaiHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(100)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="VarChar(6)")]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="VarChar(12)")]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_CT_HoaDon", Storage="_CT_HoaDons", ThisKey="maHD", OtherKey="maHD")]
		public EntitySet<CT_HoaDon> CT_HoaDons
		{
			get
			{
				return this._CT_HoaDons;
			}
			set
			{
				this._CT_HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDon", Storage="_KhachHang", ThisKey="maKH", OtherKey="maKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._maKH = value.maKH;
					}
					else
					{
						this._maKH = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon", Storage="_NhanVien", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_HoaDons(CT_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = this;
		}
		
		private void detach_CT_HoaDons(CT_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maKH;
		
		private string _tenKH;
		
		private string _sdtKH;
		
		private string _diaChi;
		
		private string _email;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    partial void OntenKHChanging(string value);
    partial void OntenKHChanged();
    partial void OnsdtKHChanging(string value);
    partial void OnsdtKHChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public KhachHang()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKH", DbType="NVarChar(30)")]
		public string tenKH
		{
			get
			{
				return this._tenKH;
			}
			set
			{
				if ((this._tenKH != value))
				{
					this.OntenKHChanging(value);
					this.SendPropertyChanging();
					this._tenKH = value;
					this.SendPropertyChanged("tenKH");
					this.OntenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdtKH", DbType="VarChar(10)")]
		public string sdtKH
		{
			get
			{
				return this._sdtKH;
			}
			set
			{
				if ((this._sdtKH != value))
				{
					this.OnsdtKHChanging(value);
					this.SendPropertyChanging();
					this._sdtKH = value;
					this.SendPropertyChanged("sdtKH");
					this.OnsdtKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(50)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(30)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDon", Storage="_HoaDons", ThisKey="maKH", OtherKey="maKH")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoThuoc")]
	public partial class LoThuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maLoThuoc;
		
		private string _maThuoc;
		
		private string _maNCC;
		
		private string _xuatXu;
		
		private System.Nullable<System.DateTime> _ngaySanXuat;
		
		private System.Nullable<System.DateTime> _hanSuDung;
		
		private string _donViTinh;
		
		private string _donViQuyDoi;
		
		private System.Nullable<int> _tyLeQuyDoi;
		
		private System.Nullable<double> _giaBanChan;
		
		private System.Nullable<double> _giaBanLe;
		
		private string _lieuLuongDung;
		
		private string _moTa;
		
		private System.Nullable<double> _VAT;
		
		private System.Nullable<int> _soLuongTon;
		
		private EntityRef<Thuoc> _Thuoc;
		
		private EntityRef<NhaCungCap> _NhaCungCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLoThuocChanging(string value);
    partial void OnmaLoThuocChanged();
    partial void OnmaThuocChanging(string value);
    partial void OnmaThuocChanged();
    partial void OnmaNCCChanging(string value);
    partial void OnmaNCCChanged();
    partial void OnxuatXuChanging(string value);
    partial void OnxuatXuChanged();
    partial void OnngaySanXuatChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySanXuatChanged();
    partial void OnhanSuDungChanging(System.Nullable<System.DateTime> value);
    partial void OnhanSuDungChanged();
    partial void OndonViTinhChanging(string value);
    partial void OndonViTinhChanged();
    partial void OndonViQuyDoiChanging(string value);
    partial void OndonViQuyDoiChanged();
    partial void OntyLeQuyDoiChanging(System.Nullable<int> value);
    partial void OntyLeQuyDoiChanged();
    partial void OngiaBanChanChanging(System.Nullable<double> value);
    partial void OngiaBanChanChanged();
    partial void OngiaBanLeChanging(System.Nullable<double> value);
    partial void OngiaBanLeChanged();
    partial void OnlieuLuongDungChanging(string value);
    partial void OnlieuLuongDungChanged();
    partial void OnmoTaChanging(string value);
    partial void OnmoTaChanged();
    partial void OnVATChanging(System.Nullable<double> value);
    partial void OnVATChanged();
    partial void OnsoLuongTonChanging(System.Nullable<int> value);
    partial void OnsoLuongTonChanged();
    #endregion
		
		public LoThuoc()
		{
			this._Thuoc = default(EntityRef<Thuoc>);
			this._NhaCungCap = default(EntityRef<NhaCungCap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoThuoc", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLoThuoc
		{
			get
			{
				return this._maLoThuoc;
			}
			set
			{
				if ((this._maLoThuoc != value))
				{
					this.OnmaLoThuocChanging(value);
					this.SendPropertyChanging();
					this._maLoThuoc = value;
					this.SendPropertyChanged("maLoThuoc");
					this.OnmaLoThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maThuoc", DbType="VarChar(11)")]
		public string maThuoc
		{
			get
			{
				return this._maThuoc;
			}
			set
			{
				if ((this._maThuoc != value))
				{
					if (this._Thuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaThuocChanging(value);
					this.SendPropertyChanging();
					this._maThuoc = value;
					this.SendPropertyChanged("maThuoc");
					this.OnmaThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNCC", DbType="VarChar(6)")]
		public string maNCC
		{
			get
			{
				return this._maNCC;
			}
			set
			{
				if ((this._maNCC != value))
				{
					if (this._NhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNCCChanging(value);
					this.SendPropertyChanging();
					this._maNCC = value;
					this.SendPropertyChanged("maNCC");
					this.OnmaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xuatXu", DbType="NVarChar(20)")]
		public string xuatXu
		{
			get
			{
				return this._xuatXu;
			}
			set
			{
				if ((this._xuatXu != value))
				{
					this.OnxuatXuChanging(value);
					this.SendPropertyChanging();
					this._xuatXu = value;
					this.SendPropertyChanged("xuatXu");
					this.OnxuatXuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySanXuat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaySanXuat
		{
			get
			{
				return this._ngaySanXuat;
			}
			set
			{
				if ((this._ngaySanXuat != value))
				{
					this.OnngaySanXuatChanging(value);
					this.SendPropertyChanging();
					this._ngaySanXuat = value;
					this.SendPropertyChanged("ngaySanXuat");
					this.OnngaySanXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hanSuDung", DbType="DateTime")]
		public System.Nullable<System.DateTime> hanSuDung
		{
			get
			{
				return this._hanSuDung;
			}
			set
			{
				if ((this._hanSuDung != value))
				{
					this.OnhanSuDungChanging(value);
					this.SendPropertyChanging();
					this._hanSuDung = value;
					this.SendPropertyChanged("hanSuDung");
					this.OnhanSuDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donViTinh", DbType="NVarChar(10)")]
		public string donViTinh
		{
			get
			{
				return this._donViTinh;
			}
			set
			{
				if ((this._donViTinh != value))
				{
					this.OndonViTinhChanging(value);
					this.SendPropertyChanging();
					this._donViTinh = value;
					this.SendPropertyChanged("donViTinh");
					this.OndonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donViQuyDoi", DbType="NVarChar(10)")]
		public string donViQuyDoi
		{
			get
			{
				return this._donViQuyDoi;
			}
			set
			{
				if ((this._donViQuyDoi != value))
				{
					this.OndonViQuyDoiChanging(value);
					this.SendPropertyChanging();
					this._donViQuyDoi = value;
					this.SendPropertyChanged("donViQuyDoi");
					this.OndonViQuyDoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tyLeQuyDoi", DbType="Int")]
		public System.Nullable<int> tyLeQuyDoi
		{
			get
			{
				return this._tyLeQuyDoi;
			}
			set
			{
				if ((this._tyLeQuyDoi != value))
				{
					this.OntyLeQuyDoiChanging(value);
					this.SendPropertyChanging();
					this._tyLeQuyDoi = value;
					this.SendPropertyChanged("tyLeQuyDoi");
					this.OntyLeQuyDoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaBanChan", DbType="Float")]
		public System.Nullable<double> giaBanChan
		{
			get
			{
				return this._giaBanChan;
			}
			set
			{
				if ((this._giaBanChan != value))
				{
					this.OngiaBanChanChanging(value);
					this.SendPropertyChanging();
					this._giaBanChan = value;
					this.SendPropertyChanged("giaBanChan");
					this.OngiaBanChanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaBanLe", DbType="Float")]
		public System.Nullable<double> giaBanLe
		{
			get
			{
				return this._giaBanLe;
			}
			set
			{
				if ((this._giaBanLe != value))
				{
					this.OngiaBanLeChanging(value);
					this.SendPropertyChanging();
					this._giaBanLe = value;
					this.SendPropertyChanged("giaBanLe");
					this.OngiaBanLeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lieuLuongDung", DbType="NVarChar(50)")]
		public string lieuLuongDung
		{
			get
			{
				return this._lieuLuongDung;
			}
			set
			{
				if ((this._lieuLuongDung != value))
				{
					this.OnlieuLuongDungChanging(value);
					this.SendPropertyChanging();
					this._lieuLuongDung = value;
					this.SendPropertyChanged("lieuLuongDung");
					this.OnlieuLuongDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moTa", DbType="NVarChar(50)")]
		public string moTa
		{
			get
			{
				return this._moTa;
			}
			set
			{
				if ((this._moTa != value))
				{
					this.OnmoTaChanging(value);
					this.SendPropertyChanging();
					this._moTa = value;
					this.SendPropertyChanged("moTa");
					this.OnmoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VAT", DbType="Float")]
		public System.Nullable<double> VAT
		{
			get
			{
				return this._VAT;
			}
			set
			{
				if ((this._VAT != value))
				{
					this.OnVATChanging(value);
					this.SendPropertyChanging();
					this._VAT = value;
					this.SendPropertyChanged("VAT");
					this.OnVATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuongTon", DbType="Int")]
		public System.Nullable<int> soLuongTon
		{
			get
			{
				return this._soLuongTon;
			}
			set
			{
				if ((this._soLuongTon != value))
				{
					this.OnsoLuongTonChanging(value);
					this.SendPropertyChanging();
					this._soLuongTon = value;
					this.SendPropertyChanged("soLuongTon");
					this.OnsoLuongTonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_LoThuoc", Storage="_Thuoc", ThisKey="maThuoc", OtherKey="maThuoc", IsForeignKey=true)]
		public Thuoc Thuoc
		{
			get
			{
				return this._Thuoc.Entity;
			}
			set
			{
				Thuoc previousValue = this._Thuoc.Entity;
				if (((previousValue != value) 
							|| (this._Thuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thuoc.Entity = null;
						previousValue.LoThuocs.Remove(this);
					}
					this._Thuoc.Entity = value;
					if ((value != null))
					{
						value.LoThuocs.Add(this);
						this._maThuoc = value.maThuoc;
					}
					else
					{
						this._maThuoc = default(string);
					}
					this.SendPropertyChanged("Thuoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_LoThuoc", Storage="_NhaCungCap", ThisKey="maNCC", OtherKey="maNCC", IsForeignKey=true)]
		public NhaCungCap NhaCungCap
		{
			get
			{
				return this._NhaCungCap.Entity;
			}
			set
			{
				NhaCungCap previousValue = this._NhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._NhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaCungCap.Entity = null;
						previousValue.LoThuocs.Remove(this);
					}
					this._NhaCungCap.Entity = value;
					if ((value != null))
					{
						value.LoThuocs.Add(this);
						this._maNCC = value.maNCC;
					}
					else
					{
						this._maNCC = default(string);
					}
					this.SendPropertyChanged("NhaCungCap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaCungCap")]
	public partial class NhaCungCap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNCC;
		
		private string _tenNCC;
		
		private string _diaChi;
		
		private string _sdt;
		
		private string _email;
		
		private System.Nullable<bool> _trangThai;
		
		private EntitySet<LoThuoc> _LoThuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNCCChanging(string value);
    partial void OnmaNCCChanged();
    partial void OntenNCCChanging(string value);
    partial void OntenNCCChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OntrangThaiChanging(System.Nullable<bool> value);
    partial void OntrangThaiChanged();
    #endregion
		
		public NhaCungCap()
		{
			this._LoThuocs = new EntitySet<LoThuoc>(new Action<LoThuoc>(this.attach_LoThuocs), new Action<LoThuoc>(this.detach_LoThuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNCC", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNCC
		{
			get
			{
				return this._maNCC;
			}
			set
			{
				if ((this._maNCC != value))
				{
					this.OnmaNCCChanging(value);
					this.SendPropertyChanging();
					this._maNCC = value;
					this.SendPropertyChanged("maNCC");
					this.OnmaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNCC", DbType="NVarChar(30)")]
		public string tenNCC
		{
			get
			{
				return this._tenNCC;
			}
			set
			{
				if ((this._tenNCC != value))
				{
					this.OntenNCCChanging(value);
					this.SendPropertyChanging();
					this._tenNCC = value;
					this.SendPropertyChanged("tenNCC");
					this.OntenNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(30)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(10)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(30)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Bit")]
		public System.Nullable<bool> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_LoThuoc", Storage="_LoThuocs", ThisKey="maNCC", OtherKey="maNCC")]
		public EntitySet<LoThuoc> LoThuocs
		{
			get
			{
				return this._LoThuocs;
			}
			set
			{
				this._LoThuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LoThuocs(LoThuoc entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = this;
		}
		
		private void detach_LoThuocs(LoThuoc entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNV;
		
		private string _tenNV;
		
		private string _sdtNV;
		
		private string _email;
		
		private string _diaChi;
		
		private string _cMND;
		
		private string _matKhau;
		
		private System.Nullable<bool> _trangThai;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OntenNVChanging(string value);
    partial void OntenNVChanged();
    partial void OnsdtNVChanging(string value);
    partial void OnsdtNVChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OncMNDChanging(string value);
    partial void OncMNDChanged();
    partial void OnmatKhauChanging(string value);
    partial void OnmatKhauChanged();
    partial void OntrangThaiChanging(System.Nullable<bool> value);
    partial void OntrangThaiChanged();
    #endregion
		
		public NhanVien()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNV", DbType="NVarChar(30)")]
		public string tenNV
		{
			get
			{
				return this._tenNV;
			}
			set
			{
				if ((this._tenNV != value))
				{
					this.OntenNVChanging(value);
					this.SendPropertyChanging();
					this._tenNV = value;
					this.SendPropertyChanged("tenNV");
					this.OntenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdtNV", DbType="VarChar(10)")]
		public string sdtNV
		{
			get
			{
				return this._sdtNV;
			}
			set
			{
				if ((this._sdtNV != value))
				{
					this.OnsdtNVChanging(value);
					this.SendPropertyChanging();
					this._sdtNV = value;
					this.SendPropertyChanged("sdtNV");
					this.OnsdtNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(30)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(50)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cMND", DbType="VarChar(20)")]
		public string cMND
		{
			get
			{
				return this._cMND;
			}
			set
			{
				if ((this._cMND != value))
				{
					this.OncMNDChanging(value);
					this.SendPropertyChanging();
					this._cMND = value;
					this.SendPropertyChanged("cMND");
					this.OncMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="VarChar(20)")]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this.OnmatKhauChanging(value);
					this.SendPropertyChanging();
					this._matKhau = value;
					this.SendPropertyChanged("matKhau");
					this.OnmatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Bit")]
		public System.Nullable<bool> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon", Storage="_HoaDons", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhomThuoc")]
	public partial class NhomThuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNhomThuoc;
		
		private string _tenNhomThuoc;
		
		private EntitySet<Thuoc> _Thuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNhomThuocChanging(string value);
    partial void OnmaNhomThuocChanged();
    partial void OntenNhomThuocChanging(string value);
    partial void OntenNhomThuocChanged();
    #endregion
		
		public NhomThuoc()
		{
			this._Thuocs = new EntitySet<Thuoc>(new Action<Thuoc>(this.attach_Thuocs), new Action<Thuoc>(this.detach_Thuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhomThuoc", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNhomThuoc
		{
			get
			{
				return this._maNhomThuoc;
			}
			set
			{
				if ((this._maNhomThuoc != value))
				{
					this.OnmaNhomThuocChanging(value);
					this.SendPropertyChanging();
					this._maNhomThuoc = value;
					this.SendPropertyChanged("maNhomThuoc");
					this.OnmaNhomThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNhomThuoc", DbType="NVarChar(20)")]
		public string tenNhomThuoc
		{
			get
			{
				return this._tenNhomThuoc;
			}
			set
			{
				if ((this._tenNhomThuoc != value))
				{
					this.OntenNhomThuocChanging(value);
					this.SendPropertyChanging();
					this._tenNhomThuoc = value;
					this.SendPropertyChanged("tenNhomThuoc");
					this.OntenNhomThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomThuoc_Thuoc", Storage="_Thuocs", ThisKey="maNhomThuoc", OtherKey="maNhomThuoc")]
		public EntitySet<Thuoc> Thuocs
		{
			get
			{
				return this._Thuocs;
			}
			set
			{
				this._Thuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Thuocs(Thuoc entity)
		{
			this.SendPropertyChanging();
			entity.NhomThuoc = this;
		}
		
		private void detach_Thuocs(Thuoc entity)
		{
			this.SendPropertyChanging();
			entity.NhomThuoc = null;
		}
	}
}
#pragma warning restore 1591
